### PR TITLE
Update headings

### PR DESCRIPTION
**Pull request by jdelamer**
#1  Update headings following: https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html#id8.
As each page was starting with a "section," I updated the subsection consequently.
I also checked that the underlines were of the size of the titles.
All the files are now following the organization below:

```
Section
=======

Subsection
----------
```

### CODE REVIEW

**Comment by jameshughes89** [comment]
The trouble is each topic title should follow

```
********************
TopicX --- something
********************
```

followed by `========` then `-----------`

**Comment by jdelamer** [comment]
It should be correct now.

**Comment by jameshughes89** [comment]
:rocket: 

Also, if you didn't notice, it now auto deploys to http://modsurski.com/csci161/

**Comment by jdelamer** [comment]
Yes, it's cool :).

**Pull request merged**
