### PR TITLE
 :lipstick:  Update css and create other admonition classes

### PR DESCRIPTION
**Pull request by jdelamer**
:lipstick: 

### Related Issues or PRs

Following #195

### What

Update the custom.css file with new admonition classes and colors.
Create a JS file to give a "mac" header to code-block and a clipboard button to copy the code.

### Why

Improve the color of the activities and other admonitions.

### Where

Everywhere.

### How

New CSS and JS files and modification of conf.py.

### Testing

image

### Additional Notes

How to use the new admonition classes:

- Activity:

```
.. admonition:: Activity
   :class: activity
```
- Example:

```
.. admonition:: Example
   :class: example
```

### CODE REVIEW

**Comment by jameshughes89** [comment]
[I checked the build artifact](https://github.com/jameshughes89/cs101/actions/runs/3934401155) and it seems that the changes did not actually make a change. See the below image. Can you build locally with sphinx to check?

image

**Comment by jameshughes89** [comment]
I really like the colours, but am questioning the mac style thing for the code. 

1. Is there specific motivation for the mac style?
2. If there is not any particular motivation, is there a way to just remove the 3 circles in the top left?

**Comment by jdelamer** [comment]
Regarding the build.
When sphinx build the website it doesn't "update" the _static folder, so the new css and js files are not copied.
I don't know if there is a command to force it.

For the mac style, there is not a specific reason. I just find it neat, but I can remove the three circles.

**Comment by jameshughes89** [comment]
> Regarding the build. When sphinx build the website it doesn't "update" the _static folder, so the new css and js files are not copied. I don't know if there is a command to force it.

Hmm... let's look into this. 

> For the mac style, there is not a specific reason. I just find it neat, but I can remove the three circles.

Let's see how it looks without the 3 circles and go from there.

**Comment by jdelamer** [comment]
Without the circles it gives the following:
image

**Comment by jameshughes89** [comment]
> Without the circles it gives the following: image

Nice. Is the copy button in the top left functional?

**Comment by jdelamer** [comment]
Yes it is.

**Comment by jdelamer** [comment]
I think the commend is ``-a`` to write every files each time.

**Comment by jameshughes89** [comment]
Just checked the artifact --- looks good. 
image
image

**Review by jameshughes89 — APPROVED** [review]

**Pull request merged**
