### PR TITLE
:bomb::bomb::bomb: "Office Hours" --- Goodbye forever 

### PR DESCRIPTION
**Pull request by jameshughes89**
### What

Remove link to twitch. 

### Why

Guess I'm just a bad streamer. Need more hot tubs.

### CODE REVIEW

**Comment by twentylemon** [comment]
If I sub will you stay

**Review by twentylemon — CHANGES_REQUESTED** [review]
no plz

**Comment by jameshughes89** [comment]
I need a hot tub

**Review by twentylemon — CHANGES_REQUESTED** [review]
STOP THE COUNT

**Comment by jdelamer** [comment]
James in a Hot Tub lol

**Comment by twentylemon** [comment]
> James in a Hot Tub lol

The things you never knew you needed

**Comment by jdelamer** [comment]
> 

The stream we need, but not the one we deserve.

**Review by twentylemon — CHANGES_REQUESTED** [review]
I've requested changes plz respond

**Comment by twentylemon** [comment]
:headstone:

**Comment by EldaveO** [comment]
This is sad, I was excited to see James in a hot tub. 👙🛁🧖‍♂️

**Comment by twentylemon** [comment]
wut

**Pull request merged**
