### PR TITLE
🎓 Models of Computation Topic clean up content

### PR DESCRIPTION
**Pull request by jameshughes89**
### What

Clean up the models of computation topic. 

### Additional Notes

Given the (well needed) additional time spend with objects, I suspect this may be the last topic discussed in the course. Time will tell though as this upcoming Fall semester will be the first run of the course since the significant rework.

### CODE REVIEW

**Comment by jameshughes89** [comment]
> I'm not sure the point, really. Throwing "yo dawg, Turing machines are a thing" at them is beyond the scope of the course. What is this priming for?

It's just mentioning it as a bookend, and high-high-level. That said, I totally feel ya'. Any specific ideas?

**Comment by twentylemon** [comment]
Not wholly sure. Anything touched on related to actual computer science will invariably be lost until 3rd/4th year when they actually start doing math. At which point, they'll need to go over it again anyways, since this introduction is surface level.

If the idea here is, "btw, this is actual computer science" -- that's also not helpful I think. Computer science still provides very good foundations for engineering, where I haven't really dealt with turing machines or that type of theory in a long time. (Though, I design grammars fairly regularly, surprisingly.) Point here is, "actual comptuer science" is academic computer science, but real "actual computer science" is both academic and applied, the degree and courses apply to both.

For this filler content, I'd revisit the course objectives, and find some stretch goals in those objectives. I don't think this content would fit those objectives. (Maybe they will -- but an argument for why would be great to see.)

**Comment by jameshughes89** [comment]
> If the idea here is, "btw, this is actual computer science" -- that's also not helpful I think. Computer science still provides very good foundations for engineering, where I haven't really dealt with turing machines or that type of theory in a long time. (Though, I design grammars fairly regularly, surprisingly.) Point here is, "actual comptuer science" is academic computer science, but real "actual computer science" is both academic and applied, the degree and courses apply to both.

I like the idea of emphasizing these ideas. Some CS academics get weirdly pissy about _PrOgRaMmInG iS nOt CoMpUtEr ScIeNcE_ and will misuse that Dijkstra quote as evidence. CS is hilariously broad, and such statements are obnoxious.

**Comment by twentylemon** [comment]
Dijkstra also authored _`goto` considered harmful_, so. Get owned, quote.

**Comment by jameshughes89** [comment]
I ended up hitting Turing Machines a little more, but still very high level. I took it as a chance to impress on them the magnitude of abstraction going on.

**Comment by twentylemon** [comment]
Impress, or frighten?

**Pull request closed without merging**
